#!/usr/bin/env python3
"""Generate a static HTML page per blog post, with social metadata baked in.

Posts used to be served from a single shell at /blog/post/?slug=<slug>, with the
title, image and body filled in by JavaScript. That works for readers and fails
completely for everyone else: LinkedIn, Facebook, X, Slack and iMessage fetch
the HTML and never run the script, so every post in the site shared as the same
untitled, imageless card. No amount of runtime <meta> juggling fixes it — the
tags have to be in the bytes the crawler is served.

So each post gets its own real page at /blog/<slug>/, carrying og: and twitter:
tags, a canonical URL and BlogPosting JSON-LD. The body is still rendered from
markdown in the browser (blog/post.js), which keeps the authoring workflow as it
was; the headline, date, byline, hero image and excerpt are written into the
HTML, so the page says something useful with JavaScript off.

Run after adding or editing a post:

    python3 tools/build_blog_pages.py

Standard library only, so the Pages workflow can run it on every deploy and a
new post can never ship without its metadata.
"""

import html
import json
import re
import shutil
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "blog" / "posts" / "manifest.json"
TEMPLATE = Path(__file__).resolve().parent / "templates" / "blog-post.html"
BLOG_DIR = ROOT / "blog"
SITE = "https://sfai.agency"

# Written into every generated file. Only directories carrying it are eligible
# for cleanup, so a hand-authored page under /blog/ is never deleted.
MARKER = "<!-- Generated by tools/build_blog_pages.py - do not edit by hand. -->"

# Directories under /blog/ that are part of the site rather than posts.
RESERVED = {"post", "posts"}

SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")

# Used when a post has no excerpt, so a share card never goes out blank.
FALLBACK_DESCRIPTION = ("News and notes from the Artificial Intelligence "
                        "Agency of San Francisco.")


def esc(value):
    """Escape for use in an HTML attribute or as text."""
    return html.escape(str(value or ""), quote=True)


def format_date(iso):
    """2026-09-08 -> September 8, 2026, matching the old client-side rendering."""
    try:
        d = date.fromisoformat(str(iso)[:10])
    except (TypeError, ValueError):
        return esc(iso)
    return f"{d.strftime('%B')} {d.day}, {d.year}"


def share_image(post):
    """Absolute URL of the post's 1.91:1 share card.

    Falls back to the raw hero image, then to the site card, so a post that
    hasn't had tools/build_share_images.py run for it still previews as
    something rather than nothing.
    """
    card = ROOT / "assets" / "share" / f"blog-{post['slug']}.jpg"
    if card.exists():
        return f"{SITE}/assets/share/{card.name}", True
    if post.get("image") and (ROOT / "blog" / post["image"]).exists():
        return f"{SITE}/blog/{post['image']}", False
    return f"{SITE}/assets/share/default.jpg", False


def json_ld(post, url, image):
    data = {
        "@context": "https://schema.org",
        "@type": "BlogPosting",
        "headline": post.get("title") or post["slug"],
        "description": post.get("excerpt") or FALLBACK_DESCRIPTION,
        "image": image,
        "datePublished": post.get("date", ""),
        "url": url,
        "mainEntityOfPage": {"@type": "WebPage", "@id": url},
        "publisher": {
            "@type": "Organization",
            "name": "SFAI.agency",
            "url": SITE + "/",
            "logo": {"@type": "ImageObject", "url": f"{SITE}/assets/logo.png"},
        },
    }
    if post.get("author"):
        data["author"] = [{"@type": "Person", "name": name.strip()}
                          for name in re.split(r"\s*&\s*|\s*,\s*", post["author"])
                          if name.strip()]
    # Keep the payload from being able to close its own <script> element.
    return (json.dumps(data, indent=8, ensure_ascii=False)
            .replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026"))


def render(post, template):
    slug = post["slug"]
    url = f"{SITE}/blog/{slug}/"
    title = post.get("title") or slug
    description = post.get("excerpt") or FALLBACK_DESCRIPTION
    image, _ = share_image(post)

    byline = ""
    if post.get("author"):
        byline = (f'<p class="post-byline" id="post-byline">'
                  f'By {esc(post["author"])}</p>')

    hero = ""
    if post.get("image"):
        hero = ('<div class="post-hero-image" id="post-hero-image">\n'
                f'                <img id="post-hero-image-img" '
                f'src="../{esc(post["image"])}" alt="{esc(title)}">\n'
                '            </div>')

    out = template
    for token, value in (
        ("{{SLUG}}", esc(slug)),
        ("{{TITLE}}", esc(title)),
        ("{{DESCRIPTION}}", esc(description)),
        ("{{URL}}", esc(url)),
        ("{{IMAGE}}", esc(image)),
        ("{{IMAGE_ALT}}", esc(title)),
        ("{{DATE}}", esc(post.get("date", ""))),
        ("{{DATE_DISPLAY}}", format_date(post.get("date"))),
        ("{{AUTHOR}}", esc(post.get("author", ""))),
        ("{{BYLINE}}", byline),
        ("{{HERO}}", hero),
        ("{{JSONLD}}", json_ld(post, url, image)),
    ):
        out = out.replace(token, value)

    leftover = re.findall(r"\{\{[A-Z_]+\}\}", out)
    if leftover:
        raise SystemExit(f"{slug}: unsubstituted tokens {sorted(set(leftover))}")
    return out.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n" + MARKER, 1)


def validate(post):
    """Split a manifest entry's problems into (fatal, cosmetic).

    Fatal means the post cannot be given a correct page and is skipped. Every
    other post still builds: one malformed entry should not cost the rest of
    the blog its metadata, or the site its deploy.
    """
    slug = post.get("slug", "")
    errors, warnings = [], []

    if not SLUG_RE.match(slug):
        errors.append(f"{slug!r}: slug must be lowercase letters, digits and hyphens")
    elif slug in RESERVED:
        errors.append(f"{slug!r}: reserved name, would collide with /blog/{slug}/")
    elif not (ROOT / "blog" / "posts" / f"{slug}.md").exists():
        errors.append(f"{slug}: blog/posts/{slug}.md is missing")

    if not post.get("title"):
        warnings.append(f"{slug}: no title; using the slug")
    if not post.get("excerpt"):
        warnings.append(f"{slug}: no excerpt; the share preview will fall back to "
                        "the site description")
    return errors, warnings


def stale_dirs(slugs):
    """Generated post directories no longer backed by the manifest."""
    for child in sorted(BLOG_DIR.iterdir()):
        if not child.is_dir() or child.name in RESERVED or child.name in slugs:
            continue
        index = child / "index.html"
        if index.exists() and MARKER in index.read_text(encoding="utf-8"):
            yield child


def main():
    template = TEMPLATE.read_text(encoding="utf-8")
    posts = json.loads(MANIFEST.read_text(encoding="utf-8"))

    failed, warnings, built = [], [], []
    for post in posts:
        errors, notes = validate(post)
        warnings.extend(notes)
        if errors:
            for e in errors:
                print(f"  error: {e}", file=sys.stderr)
            failed.append(post.get("slug", "?"))
            continue

        out_dir = BLOG_DIR / post["slug"]
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "index.html").write_text(render(post, template), encoding="utf-8")
        built.append(post["slug"])

        _, has_card = share_image(post)
        if not has_card:
            warnings.append(f"{post['slug']}: no 1200x630 share card; "
                            "run tools/build_share_images.py")
        print(f"  blog/{post['slug']}/index.html"
              + ("" if has_card else "  (no share card)"))

    # Only sweep when every post built: a skipped post must not have its
    # existing, working page deleted out from under it.
    if not failed:
        for stale in stale_dirs(set(built)):
            shutil.rmtree(stale)
            print(f"  removed stale blog/{stale.name}/")

    print(f"Built {len(built)} post pages.")
    for w in warnings:
        print(f"  warning: {w}", file=sys.stderr)
    if failed:
        print(f"Skipped {len(failed)} post(s): {', '.join(failed)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
